# render.yaml
services:
  # ===== PostgreSQL Database =====
  - type: pserv
    name: postgres-db
    plan: free
    region: singapore
    # ❌ ipAllowList 제거 (pserv는 지원 안 함)

  # ===== FastAPI Backend =====
  - type: web
    name: fastapi-backend
    runtime: docker
    plan: free
    region: singapore
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: ./backend
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
    autoDeploy: true

  # ===== React Frontend =====
  - type: web
    name: react-frontend
    runtime: docker
    plan: free
    region: singapore
    branch: main
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: REACT_APP_API_URL
        # ❌ url 속성 없음!
        # ✅ 수동으로 Backend URL 입력하거나
        # ✅ 배포 후 Environment에서 설정
        value: https://fastapi-backend.onrender.com
    autoDeploy: true