projects: 
  - name: My-app 
    environments: 
      - name: production
        databases:
          - name: postgres-db
            plan: free
            region: singapore
        services: 
          - type: web 
            name: fastapi-server 
            runtime: docker 
            region: singapore
            plan: free
            branch: main
            rootDir: backend
            dockerfilePath: ./Dockerfile
            dockerContext: .
            envVars: 
              - key: DB_URL
                fromDatabase: 
                  name: postgres-db
                  property: connectionString
            autoDeploy: true

          - type: web 
            name: react-server
            runtime: docker
            region: singapore
            plan: free
            branch: main
            rootDir: frontend 
            dockerfilePath: ./Dockerfile
            dockerContext: .
            envVars: 
              - key: API_SERVER_URL
                fromService: 
                  type: web 
                  name: fastapi-server
                  property: host
            autoDeploy: true