# render.yaml
services:
  # ===== PostgreSQL Database =====
  - type: postgres
    name: postgres-db
    plan: free
    region: singapore
    ipAllowList: []

  # ===== FastAPI Backend =====
  - type: web
    name: fastapi-backend
    runtime: docker
    plan: free
    region: singapore
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
    autoDeploy: true

  # ===== React Frontend =====
  - type: web
    name: react-frontend
    runtime: docker
    plan: free
    region: singapore
    branch: main
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: fastapi-backend
          property: host
    autoDeploy: true